const { Maintenance } = require('../models');

const maintenanceData = [
    {
        record: 1,
        area: 'Sanding',
        equipment: 'Tumbler',
        requestType: 'Routine',
        description: 'Automatic Water Solenoid Valve - Water does not come on, valve may not be getting 24 volts to open or valve is broke',
        approvedBy: 'Brent Whittaker',
        repairedBy: 'Scott',
        repairDescription: 'Replace saftey switch',
        comments: 'Moved this over to electrician spread sheet',
        done: 1,
        createdAt: '2022-12-07',
    },
    {
        record: 51,
        requestedBy: 'James Wilkins',
        area: 'Welding',
        equipment: 'Welding',
        createdAt: '2023-02-06',
        requestType: 'Routine',
        description: 'Welding Project',
        approvedBy: 'Brent Whittaker',
        repairDescription: 'Build Argon Gas Post',
        comments: 'Powder Coat Weld Posts / Prefab Argon Copper line (Ken has bill of materials) -02/14/23 2/8 stand is done prefab lines are almost done waiting for elbows to complete',
    },
    {
        record: 52,
        requestedBy: 'James Wilkins',
        area: 'Building',
        equipment: 'HVAC',
        createdAt: '2023-02-06',
        requestType: 'Routine',
        description: 'HVAC Project',
        approvedBy: 'Brent Whittaker',
        repairedBy: 'Jon Streeter',
        comments: 'Identify All Units on HVAC Guide (HVAC Map - man lift) - 02/09/23',
    },
    {
        record: 59,
        requestedBy: 'Adrian Ayaquica',
        area: 'Laser',
        equipment: 'Mitsubishi CO2',
        createdAt: '2023-02-16',
        requestType: 'Planned',
        description: 'Height Sensor Error',
        approvedBy: 'Brent Whittaker',
    },
    {
        record: 70,
        requestedBy: 'Daniel Ahumada',
        area: 'Shipping',
        equipment: 'DOSAN FORKLIFT',
        createdAt: '2023-03-08',
        requestType: 'Routine',
        description: 'Forklift dies when you try to accelerate',
        approvedBy: 'Jon Streeter',
    },
    {
        record: 71,
        requestedBy: 'Troy Naberhaus',
        area: 'Welding',
        equipment: 'SYNCROWAVE 350LX (1)',
        createdAt: '2023-03-13',
        requestType: 'Routine',
        description: 'High frequenct start sputters. Send to General Air',
        approvedBy: 'Brent Whittaker',
    },
    {
        record: 72,
        requestedBy: 'Troy Naberhaus',
        area: 'Welding',
        equipment: 'IPG LASER WELDER',
        createdAt: '2023-03-13',
        requestType: 'Routine',
        description: 'Laser gun inconsistent. Hose/Wires have to be held in position to work. Send to General Air',
        approvedBy: 'Brent Whittaker',
    },
];

const seedMaintenance = () => Maintenance.bulkCreate(maintenanceData);

module.exports = seedMaintenance;